version: 2.1

jobs:
  'Build - Ruby 3_0':
      docker:
        - image: circleci/ruby:3.0.0
      steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Install Bundler
          command: gem install bundler:2.2.13
      - restore_cache:
          keys:
            - gem-cache-ruby-3-v1{{ checksum "Gemfile.lock" }}
            - gem-cache-ruby-3
      - run:
          name: Bundle Install
          command: bundle check || bundle install --without production
      - save_cache:
          key: gem-cache-ruby-3-v1{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: 'Lint: Rubocop'
          command: bundle exec rubocop .
      - run:
          name: Run RSpec
          command: bundle exec rspec spec
      - store_test_results:
          path: test_results

  'Build - Ruby 2_7_3':
      docker:
        - image: circleci/ruby:2.7.3
      steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Install Bundler
          command: gem install bundler:2.2.13
      - restore_cache:
          keys:
            - gem-cache-ruby-2-7-3-v1{{ checksum "Gemfile.lock" }}
            - gem-cache-ruby-2-7-3
      - run:
          name: Bundle Install
          command: bundle check || bundle install --without production
      - save_cache:
          key: gem-cache-ruby-2-7-3-v1{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: 'Lint: Rubocop'
          command: bundle exec rubocop .
      - run:
          name: Run RSpec
          command: bundle exec rspec spec
      - store_test_results:
          path: test_results

workflows:
  version: 2
  build:
    jobs:
      - 'Build - Ruby 3_0'
      - 'Build - Ruby 2_7_3'
